### ISSUE TITLE
How do you get the VIST dataset?

### ISSUE THREAD

**Issue by jacob-kang** [eric-ai-lab/MiniGPT-5#1]

**Comment by KzZheng** [comment]
Hi,

You can download the [labeled data](https://visionandlanguage.net/VIST/json_files/story-in-sequence/SIS-with-labels.tar.gz) from their website. It includes the image links. Then, you can use [img2dataset](https://github.com/rom1504/img2dataset) to download all images.

Thanks,
Kaizhi
