### ISSUE TITLE
Bad performance on example

### ISSUE THREAD

**Issue by Changhy1996** [eric-ai-lab/MiniGPT-5#10]
Hello, I tried to load the model and run the example, but the text generated seems wrong.

Below is the generated text:
```
Generated text: <unk> [IMG0] [IMG7] [IMG0] that [IMG0] their [IMG0] ihrer there are fait leurt, [IMG0] they sont ihrréms [IMG0] ihre lui eran in Mame
## the barbec [IMG0] his été herem'rs."> [IMG0] их themselves_\thereir is their sein_mâ [IMG0] loro were him its\ seu_. ###
```
Besides, the image generated looks also weird, but better than the text.

I ran this code on a jupyter notebook, the code reports no bug.  Do you have any idea how this is caused?

Thank.

**Comment by KzZheng** [comment]
Hi,

When you try the example, you need to set the environment variable `export IS_STAGE2=True` or manually change the `IS_STAGE2` variable in constants.py to True.

Best,
Kaizhi

**Comment by Changhy1996** [comment]
Thanks for your reply,

Once I set IS_STAGE2=True, another bug triggered while loading Llama:

```
AttributeError: 'Embedding' object has no attribute 'original_module'
AttributeError: 'Linear' object has no attribute 'original_module'
```
in minigpt4.models.mini_gpt5.py line115:
self.llama_model.base_model.model.model.embed_tokens.original_module.weight.requires_grad = False

Can I just delete this?

Thanks again.

**Comment by KzZheng** [comment]
My Peft version is 0.5.0, and your Peft 0.4.0 should be fine since you can generate the correct text. I think the reason for the image issue is that you do not load the stage_1 checkpoint correctly. It is important that the model needs to load the stage_1 checkpoint first and then replace some of the weights with the stage_2 checkpoint. I attached my output below. You can try to run playground.py first instead of using jupyter notebook.

```bash
Global seed set to 42
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA
Loading checkpoint shards: 100%|█████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.52s/it]
Loading LLAMA Done
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embedding dimension will be 32009. This might induce some performance reduction as *Tensor Cores* will not be available. For more details about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
Using LoRA
Load BLIP2-LLM Checkpoint: ./config/prerained_minigpt4_7b.pth
Loading pipeline components...: 100%|████████████████████████████████████████████| 6/6 [00:00<00:00,  9.53it/s]
/home/kaizhi/.conda/envs/minigpt5_env/lib/python3.9/site-packages/lightning/pytorch/core/saving.py:165: UserWarning: Found keys that are not in the model state dict but in the checkpoint: ['model.llama_model.model.embed_tokens.weight', 'model.llama_model.lm_head.weight']
  rank_zero_warn(
Backend TkAgg is interactive backend. Turning interactive mode on.
Generated text: i had everything we needed , it was going to be an excellent bar bq . [IMG0] ###
100%|██████████████████████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 19.80it/s]
```

**Comment by Changhy1996** [comment]
Seems like works, thank you.

A <unk> token leads the text, and the image still shows a little difference.
Below is my output.
![download](https://github.com/eric-ai-lab/MiniGPT-5/assets/48384202/fa91d6bf-251b-4466-a74e-068a76073251)

**Comment by KzZheng** [comment]
This may be caused by the Transformers version. You can try transformers==4.31.0
