### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by lewisliuyi** [eric-ai-lab/MiniGPT-5#11]
I try to run "python3 playground.py --stage1_weight WEIGHT_FOLDER/stage1_cc3m.ckpt",but it shows the ckpt cannot load normally like the title. I suspect the ckpt files is broken or I have a wrong version of pytorch.

**Comment by KzZheng** [comment]
Do you change the WEIGHT_FOLDER to the correct path? Also, you need to load stage2_weight for the playground.  Another person in #10 just successfully ran the demo.

**Comment by lewisliuyi** [comment]
No, it doesn't work. I see the error is just about "stage1_cc3m.ckpt" in the "playground.py" line 40.

**Comment by KzZheng** [comment]
The uploaded weight is correct. Can you try torch==2.0.1?

**Comment by lewisliuyi** [comment]
no，I guess because my conda get a low version cuda 11080

**Comment by lewisliuyi** [comment]
my cude version is 11.8 and i got a warning of low version. is that the reason?

**Comment by KzZheng** [comment]
I don't think so. My cuda version is 11.7, even lower than your version.
