### ISSUE TITLE
a question about inference, no "output_img_token" (playground.py)

### ISSUE THREAD

**Issue by FromA2Z** [eric-ai-lab/MiniGPT-5#13]
Regarding the inference effect, in my experiment, there was only [IMG2] in the generated text, but not [IMG0]. I wonder if this is normal. Because [IMG0] means "output_img_id", without it you cannot enter the image generation branch. Looking forward to your answer, thankyou。
![image](https://github.com/eric-ai-lab/MiniGPT-5/assets/108920982/357e19ae-3257-489b-9e07-ac64baabae99)
![image](https://github.com/eric-ai-lab/MiniGPT-5/assets/108920982/e6d1cc12-e93f-4c3b-a66c-e874c5b67f78)

**Comment by KzZheng** [comment]
Yes, the model will generate an image only when [IMG0] is predicted. This error may be caused by the newest transformers library (They update the tokenizer), Maybe you can try transformers=4.31.0. Thanks!

**Comment by FromA2Z** [comment]
> Yes, the model will generate an image only when [IMG0] is predicted. This error may be caused by the newest transformers library (They update the tokenizer), Maybe you can try transformers=4.31.0. Thanks!

Thank you for your answer. It was indeed a version problem. I changed the version of the transformer and the problem was solved.
