### ISSUE TITLE
Absolute Path in file "MiniGPT-5/datasets/CC3M/cc3m_val_8-token_stage1.pkl"

### ISSUE THREAD

**Issue by Norman-Ou** [eric-ai-lab/MiniGPT-5#16]
As below
![image](https://github.com/eric-ai-lab/MiniGPT-5/assets/81309187/ef002b85-796a-4ad1-ae0b-6b72d7a053ae)

**Comment by KzZheng** [comment]
Oh, sorry. This file should not be uploaded. It should be generated by yourself. I will delete this file in the repo.
