### ISSUE TITLE
Enhancement about SDXL/ LLAMA-2

### ISSUE THREAD

**Issue by George0726** [eric-ai-lab/MiniGPT-5#19]
Hi author,
thanks for your impressive work! are you planning to pre-train the work on more strengthful submodule, like LLAMA-2 and SDXL?

**Comment by KzZheng** [comment]
Thanks for your attention! Due to the limited resources, we do not plan to re-train the model on larger models. We will release the weights if we do that later. Thanks!

**Comment by George0726** [comment]
Thanks for replying.
