### ISSUE TITLE
The GPT-5 from OpenAI hasn't been released yet, adopting such a name. Can the AI research community not be so impetuous?

### ISSUE THREAD

**Issue by junzhan18** [eric-ai-lab/MiniGPT-5#2]

**Comment by KzZheng** [comment]
Thanks for your attention to this work! Compared to the [MiniGPT-4](https://github.com/Vision-CAIR/MiniGPT-4), our model extends the output space to multimodality, and we think that will be the correct direction for the [next generation LLMs](https://openai.com/research/gpt-4v-system-card). Therefore, we named MiniGPT-5 based on MiniGPT-4. Thanks for your question again!
