### ISSUE TITLE
Acknowledgement on LAVIS

### ISSUE THREAD

**Issue by dxli94** [eric-ai-lab/MiniGPT-5#20]
Hi authors,

It seems the codebase has overlaps with LAVIS. In fact, MiniGPT-4 is largely built on our library.

Would you mind if updating the arxiv manuscript and README with reference to the LAVIS library?

Thanks.

**Comment by KzZheng** [comment]
Thanks for your reminder! We have updated the README with reference to the LAVIS library. For the arxiv, we will update the reference in the next revision.
