### ISSUE TITLE
the value of hidden_states in modeling_llama.py line 689 is NAN!!

### ISSUE THREAD

**Issue by skyboy23** [eric-ai-lab/MiniGPT-5#27]
Hello, when I ran your program, I found the value of hidden_states in modeling_llama.py line 689 is NAN!!

I triggered this bug when running playground.py. I used the official parameters for all settings. Just because my video memory is only 24GB, I set low_source=True in minigpt4.

**Comment by KzZheng** [comment]
I tried to use the 8-bit weights of MiniGPT-4, and I also got NaN values in hidden_states. I think our current fine-tuned weight (LoRA weight) does not support mixing with 8-bit pretrained weights.

In my local test, the model uses 23229 MB VRAM. Maybe your GPU can directly load it.

**Comment by skyboy23** [comment]
I got it, thank you so much.
