### ISSUE TITLE
TypeError: Unexpected type <class 'NoneType'>

### ISSUE THREAD

**Issue by moonbaby9** [eric-ai-lab/MiniGPT-5#28]
Thanks for your wonderful work!
I try to run "python3 metric.py --test_weight stage2_mmdialog.ckpt", but encountered the following error：
TypeError: Unexpected type <class 'NoneType'>
I will be greatly appreciate if you could help me solve the error.

**Comment by KzZheng** [comment]
Can you check whether you have 'predictions-*.pt' files under "OUTPUT_FOLDER/stage2_mmdialog" folder? These files should be generated after you finish the evaluation step. To calculate metrics, the prediction list should not be empty after [line 385](https://github.com/eric-ai-lab/MiniGPT-5/blob/cdd6f6f90b3dfd5dab312b92b25e4a7bb5db8843/metric.py#L385).

Also, remember to keep the environment variables, like
```bash
export DATAFOLDER=datasets/MMDialog
export OUTPUT_FOLDER=outputs
```

**Comment by moonbaby9** [comment]
Thank you very much!
