### ISSUE TITLE
ABOUT GPU RAM

### ISSUE THREAD

**Issue by VTaPo** [eric-ai-lab/MiniGPT-5#31]
I run the playground.py file with 16GB of GPU ram but it's still not enough. Can you show me some ways to still run files but without needing 16GB of GPU ram?

**Comment by zhangwengyu999** [comment]
Similar problem, I run the playground.py with 24GB GPU RAM, it still gives `torch.cuda.OutOfMemoryError`.

**Comment by KzZheng** [comment]
Thanks for your attention to this work. I have updated the playground.py for model loading so that 24GB VRAM should be available to run, but I have no idea how to make it run on 16GB VRAM for now. I'm sorry about that.

**Comment by VTaPo** [comment]
Thank you for your response
