### ISSUE TITLE
[BUG]Hello, there was an error (TypeError: unsupported operand type (s) for//: 'NoneType' and 'int') running Python playground.py

### ISSUE THREAD

**Issue by lckj2009** [eric-ai-lab/MiniGPT-5#32]
Operating system: ubuntu 20.04

Python 3.9.18

Other parameters: Same as MiniGPT-5/requirements. txt

All three ckpt files are located in MiniGPT-5/config. The configuration files have been changed. The weight used is vicuna-7b-v1.1. However, the following error still occurred.

Run Python playground.py -- stage1_ Weight /root/MiniGPT-5/config/stage1_ Cc3m.ckpt -- test_ Weight /root/MiniGPT-5/config/stage2_ The following error occurred during the visit.ckpt command:

Seed set to 42
Loading VIT
Traceback (most recent call last):
  File "/root/MiniGPT-5/examples/playground.py", line 40, in <module>
    minigpt5 = MiniGPT5_Model.load_from_checkpoint(stage1_ckpt, strict=False, map_location="cpu", encoder_model_config=model_args, **vars(training_args))
  File "/root/anaconda3/envs/minigpt5/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1552, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/root/anaconda3/envs/minigpt5/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 89, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/root/anaconda3/envs/minigpt5/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 156, in _load_state
    obj = cls(**_cls_kwargs)
  File "/root/MiniGPT-5/model.py", line 68, in __init__
    self.model = MiniGPT5.from_config(minigpt4_config.model_cfg)
  File "/root/MiniGPT-5/minigpt4/models/mini_gpt4.py", line 247, in from_config
    model = cls(
  File "/root/MiniGPT-5/minigpt4/models/mini_gpt5.py", line 46, in __init__
    super().__init__(*args, **kwargs)
  File "/root/MiniGPT-5/minigpt4/models/mini_gpt4.py", line 53, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "/root/MiniGPT-5/minigpt4/models/blip2.py", line 65, in init_vision_encoder
    visual_encoder = create_eva_vit_g(
  File "/root/MiniGPT-5/minigpt4/models/eva_vit.py", line 416, in create_eva_vit_g
    model = VisionTransformer(
  File "/root/MiniGPT-5/minigpt4/models/eva_vit.py", line 259, in __init__
    self.patch_embed = PatchEmbed(
  File "/root/MiniGPT-5/minigpt4/models/eva_vit.py", line 190, in __init__
    num_patches = (img_size[1] // patch_size[1]) * (img_size[0] // patch_size[0])
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

**Comment by KzZheng** [comment]
I'm not sure about the reasons for this issue. Can you try the same version of some of my libraries: `torch==2.0.1`, `lightning==2.0.9.post0`.

Also, can you stage1_ckpt path is correctly loaded?

**Comment by TongLiu-github** [comment]
> Operating system: ubuntu 20.04
> 
> Python 3.9.18
> 
> Other parameters: Same as MiniGPT-5/requirements. txt
> 
> All three ckpt files are located in MiniGPT-5/config. The configuration files have been changed. The weight used is vicuna-7b-v1.1. However, the following error still occurred.
> 
> Run Python playground.py -- stage1_ Weight /root/MiniGPT-5/config/stage1_ Cc3m.ckpt -- test_ Weight /root/MiniGPT-5/config/stage2_ The following error occurred during the visit.ckpt command:
> 
> Seed set to 42 Loading VIT Traceback (most recent call last): File "/root/MiniGPT-5/examples/playground.py", line 40, in minigpt5 = MiniGPT5_Model.load_from_checkpoint(stage1_ckpt, strict=False, map_location="cpu", encoder_model_config=model_args, **vars(training_args)) File "/root/anaconda3/envs/minigpt5/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1552, in load_from_checkpoint loaded = _load_from_checkpoint( File "/root/anaconda3/envs/minigpt5/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 89, in _load_from_checkpoint model = _load_state(cls, checkpoint, strict=strict, **kwargs) File "/root/anaconda3/envs/minigpt5/lib/python3.9/site-packages/lightning/pytorch/core/saving.py", line 156, in _load_state obj = cls(**_cls_kwargs) File "/root/MiniGPT-5/model.py", line 68, in **init** self.model = MiniGPT5.from_config(minigpt4_config.model_cfg) File "/root/MiniGPT-5/minigpt4/models/mini_gpt4.py", line 247, in from_config model = cls( File "/root/MiniGPT-5/minigpt4/models/mini_gpt5.py", line 46, in **init** super().**init**(*args, **kwargs) File "/root/MiniGPT-5/minigpt4/models/mini_gpt4.py", line 53, in **init** self.visual_encoder, self.ln_vision = self.init_vision_encoder( File "/root/MiniGPT-5/minigpt4/models/blip2.py", line 65, in init_vision_encoder visual_encoder = create_eva_vit_g( File "/root/MiniGPT-5/minigpt4/models/eva_vit.py", line 416, in create_eva_vit_g model = VisionTransformer( File "/root/MiniGPT-5/minigpt4/models/eva_vit.py", line 259, in **init** self.patch_embed = PatchEmbed( File "/root/MiniGPT-5/minigpt4/models/eva_vit.py", line 190, in **init** num_patches = (img_size[1] // patch_size[1]) * (img_size[0] // patch_size[0]) TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

Same error, how did you solve this?
