### ISSUE TITLE
OSError: Can't load tokenizer for 'E:\models--Vision-CAIR--vicuna-7b' but my local file exists

### ISSUE THREAD

**Issue by AnYiYa6** [eric-ai-lab/MiniGPT-5#36]
Because the model was too large, I downloaded it to the local E disk and modified the path. When I ran the example, it prompted me that there was no problem with the path. How should I solve it?
![Snipaste_2023-11-30_16-31-06](https://github.com/eric-ai-lab/MiniGPT-5/assets/152484101/ecfcb13b-7e07-4dbe-8a05-e2e8fc8708df)
The picture below is my error report
![Snipaste_2023-11-30_17-06-38](https://github.com/eric-ai-lab/MiniGPT-5/assets/152484101/d24a9fea-7969-4b19-8f31-6da2f21ada29)

**Comment by KzZheng** [comment]
Sorry, I didn't use Windows to run the model before and I'm not sure which part leads to this error. Can you check whether you can load some hf models first, like [LLAMA2](https://huggingface.co/docs/transformers/model_doc/llama2)?

**Comment by AnYiYa6** [comment]
> Sorry, I didn't use Windows to run the model before and I'm not sure which part leads to this error. Can you check whether you can load some hf models first, like [LLAMA2](https://huggingface.co/docs/transformers/model_doc/llama2)?

Thank you for your answer. I have solved this problem because there are other model files and configuration files that I have not downloaded locally. I just need to fill in the missing files.

**Comment by AnYiYa6** [comment]
> Sorry, I didn't use Windows to run the model before and I'm not sure which part leads to this error. Can you check whether you can load some hf models first, like [LLAMA2](https://huggingface.co/docs/transformers/model_doc/llama2)?

But I have a new question, why is there a lot of garbled characters in the text I generated, and I don’t know which country’s language it is generated in. Where should I modify it to let it output the language I need and solve the garbled code problem.
![Snipaste_2023-12-01_10-06-48](https://github.com/eric-ai-lab/MiniGPT-5/assets/152484101/d72d0449-cfaf-43af-bb1f-ed266e69ea93)

**Comment by KzZheng** [comment]
There may be several potential reasons for this issue:
1. Wrong transformers library version: `transformers==4.31.0` should be a working version
2. Forget to set environment variable `IS_STAGE2`: Please check whether `IS_STAGE2=True` before you load the model. You also can manually set it to True in the `constants.py`
3. Stage-1 or Stage-2 weights are not correctly loaded: Please check the path to see whether the model loads the correct weights.

You can check these reasons one by one. My guess is the second reason.
