### ISSUE TITLE
Construction of dataset

### ISSUE THREAD

**Issue by Zeqiang-Lai** [eric-ai-lab/MiniGPT-5#37]
Thanks for releasing your great work!

I am a little confused why you construct conversation every 100 samples in CC3M dataset  

https://github.com/eric-ai-lab/MiniGPT-5/blob/d945c9354cd3adb7c184cb4ce9a57ad50f530923/dataloader.py#L63

Is this some kind of data augmentation strategy?

**Comment by KzZheng** [comment]
Yes, since Vicuna already used instruction tuning data, we constructed similar data to help model adaption.
