### ISSUE TITLE
vision encoder used in MiniGPT-5

### ISSUE THREAD

**Issue by dylanqyuan** [eric-ai-lab/MiniGPT-5#40]
Nice work!
We develop a benchmark for evaluating MLLM. We wanna report MiniGPT-5 on this benchmark~
I wonder what Vision Encoder used in MiniGPT-5? same as MiniGPT-4(EVA-G or something)? :satisfied:

**Comment by KzZheng** [comment]
We use the same as MiniGPT-4, which includes ViT and Qformer.
