### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.models.vae'

### ISSUE THREAD

**Issue by FanqingM** [eric-ai-lab/MiniGPT-5#41]
in model.py:
from diffusers import StableDiffusionPipeline
from diffusers.models.vae import DiagonalGaussianDistribution

ModuleNotFoundError: No module named 'diffusers.models.vae'

Is there something wrong with the version?

**Comment by KzZheng** [comment]
My diffusers==0.21.4. Maybe you can try this version.
