### ISSUE TITLE
Poor generation results (with normal text and image outputs)

### ISSUE THREAD

**Issue by TongLiu-github** [eric-ai-lab/MiniGPT-5#44]
Hi, 
Your work will be highly cited. 

When I run playground.py, it generates the following results. 

![image](https://github.com/eric-ai-lab/MiniGPT-5/assets/66426972/ea620d55-1849-4674-b221-298be98953ba)
![image](https://github.com/eric-ai-lab/MiniGPT-5/assets/66426972/afbe9c8d-c9cd-48cd-9b53-8f8c4ab8042d)

The only change from me is that 
"self.image_pipeline.to(self.device, PRECISION)"
->
"self.image_pipeline.to(self.device)"
Since otherwise, it leads to errors:
"TypeError: to() takes from 1 to 2 positional arguments but 3 were given"

The following is the log that I have when running the code: 
Seed set to 42
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.95s/it]Loading LLAMA Done
Load BLIP2-LLM Checkpoint: ./config/prerained_minigpt4_7b.pth
text_encoder/pytorch_model.fp16.safetensors not found
Fetching 16 files: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 16648.19it/s]/opt/conda/envs/minigpt5/lib/python3.9/site-packages/transformers/generation/utils.py:1270: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
Generated text: <unk> [IMG0] [IMG7] [IMG0] ' [IMG0] their [IMG0] ihrer to me what thet, [IMG0] leur sont ihrr a [IMG0] eux them there that they have been [IMG0] ihnen who him est her his [IMG0] lui ihm he knew. sizing of themselves_\_, [IMG0] quien er sein hé was_their loro manière in de seu_.
their étaient zijn làb _ [IMG0] Their'_s [IMG0] deren\_they était à érthé ihre were on [IMG0] 的 ellos [IMG0] hers at it è your are an étant eren had died [IMG0] på [IMG0] whose ép eran cél son era thé års éeʁ� space sua∂._Picame one\? [IMG0] whom she is__er их essereт у pénêtrement [IMG0] erano haar [IMG0] when der ils där careerés le témère than étéιם from fait méa Théria! [IMG0] 452 [IMG0] -toème its own fé détéré vériti and eenérném [IMG0] their están being_\ερן" about you [IMG0] -ed himself déjà< for many… They hade said élőрσи в theorem을.< One might be having arrived; [IMG0] estaba involved____ thing [IMG0] made the seus mědété que être un péner rég—himselfétait býlэ _, perché celuiה들αre�
100%|████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 18.50it/s]/home/VD/tong/mmreasoning/MiniGPT-5/./examples/playground.py:81: UserWarning: Glyph 30340 (\N{CJK UNIFIED IDEOGRAPH-7684}) missing from current font.
  plt.savefig(os.path.join(current_dir, f'test_{i}.png'), bbox_inches='tight')
/home/VD/tong/mmreasoning/MiniGPT-5/./examples/playground.py:81: UserWarning: Glyph 51012 (\N{HANGUL SYLLABLE EUL}) missing from current font.
  plt.savefig(os.path.join(current_dir, f'test_{i}.png'), bbox_inches='tight')
/home/VD/tong/mmreasoning/MiniGPT-5/./examples/playground.py:81: UserWarning: Glyph 46308 (\N{HANGUL SYLLABLE DEUL}) missing from current font.
  plt.savefig(os.path.join(current_dir, f'test_{i}.png'), bbox_inches='tight')
Generated text: <unk> [IMG0] [IMG7] [IMG0] and [IMG0] de was [IMG0] were their seat, [IMG0] there in the bq [IMG0] your [IMG0] she était involved [IMG0] you for him zijnb q bý is it een [IMG0] hering qu's bar estaba his été one of lui [IMG0] deren he had been a là quelle étaient its sein_\him.##
there are many měre sich dessen? [IMG0] that_er they would have è _ théirheimt_.``` [IMG0] leuré eux to be héi meme themselves._ [IMG0] those sont seu… loro erano în quel_, där\_mε étant; being é méthèmeréd by Me [IMG0] Thea membre who stée être leurs car era 1 [IMG0] One Man [IMG0] There termed [IMG0] Their Party [IMG0] -à [IMG0] has [IMG0] Théเתה명�� from scene [IMG0] Étه knew about them was herself_his name [IMG0] They'd himself в this moment célhey的 scène [IMG0] their hétself à elle его fame—they�� _, which made hisэρ들יσе, [IMG0] на la ép y léς on elـe pén son — sua_\_; me��вן i원을 suo= [IMG0] That man' story told everyone but ihn,---\the air_\θ [IMG0] whose family
100%|████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:03<00:00, 16.30it/s]
...

Is there any thing that I could do to improve the result?

**Comment by TongLiu-github** [comment]
> From your results, it seems you do not set IS_STAGE2=True as environment variables. You can check issue #10 for more discussion.

woops, thank you! Now everything fine :)

**Comment by TongLiu-github** [comment]
Now the examples in playground.py worked. But maybe one more question regarding the generation, I found quite often, minigpt5 does not generate the text and only generate the image.
Is there any thing that I could do to improve the result?
e.g., 
![image](https://github.com/eric-ai-lab/MiniGPT-5/assets/66426972/90e587bd-0581-40e5-b3e5-fccae9024edf)
![image](https://github.com/eric-ai-lab/MiniGPT-5/assets/66426972/c5ed9c6b-1bdb-4ed0-9f62-93ddedf25c44)

where the text part is only <unk>.

**Comment by KzZheng** [comment]
Since our model only finetuned on the VIST dataset with templated instructions, the model's generalizability is limited. It is an interesting follow-up direction about how to improve the model's usage of pretrained commonsense knowledge.

**Comment by ALR-alr** [comment]
> > From your results, it seems you do not set IS_STAGE2=True as environment variables. You can check issue #10 for more discussion.
> 
> woops, thank you! Now everything fine :)

Did you succeed? When I set IS_STAGE2 to True, I got the same bad performed output.
