### ISSUE TITLE
Question about garbled text

### ISSUE THREAD

**Issue by witnessai** [eric-ai-lab/MiniGPT-5#46]
Thank you for your fascinating work. I have a question regarding our experience using MiniGPT-5 to train on our dataset. We've noticed that the output contains garbled text (as shown in the figure below). Could you please advise on what might be causing this issue? 
![text](https://github.com/eric-ai-lab/MiniGPT-5/assets/8973603/3151fee7-556b-4d95-b07a-4fdc2d023e22)

**Comment by KzZheng** [comment]
Do you use our pretrained parameters or your fine-tuned ones? It looks like the error that you do not set IS_STAGE=True in your environment variables. You can check issue #10 for more discussion.

**Comment by witnessai** [comment]
thanks for the reply, it turns out that the main issue is with the version of peft.
