### ISSUE TITLE
STAGE 1 TRAINING 

### ISSUE THREAD

**Issue by srymaker** [eric-ai-lab/MiniGPT-5#47]
Thank you for your great work!
In the stage 1 training mentioned in the paper, is the input of llm images and text，because the description ‘After the pretraining stage, the model is capable of generating images for single text descriptions’  in the article is unimodal?
And,What does ‘The Language Model (LLM) is then tasked with only generating these placeholders for text creation’ mean? Does the stage 1 llm only need to generate placeholders without other token embedding?

**Comment by KzZheng** [comment]
The unimodal here just means we only learn texts to image alignment in stage 1. I hope this figure can help you out.

![Screenshot from 2024-04-25 13-36-00](https://github.com/eric-ai-lab/MiniGPT-5/assets/62070113/84622fa4-8d4d-4b77-9cca-b6bd1d4a625a)
