### ISSUE TITLE
What kind of GPU does MiniGPT-5 need?

### ISSUE THREAD

**Issue by axbing** [eric-ai-lab/MiniGPT-5#5]
What kind of GPU does MiniGPT-5 need?

**Comment by KzZheng** [comment]
For training, we use 4 A6000(48G) GPUs. For evaluation, it can run on the A5000(24G) GPUs.

**Comment by jmanhype** [comment]
thank you

**Comment by axbing** [comment]
Thank you @KzZheng .

**Comment by jmanhype** [comment]
What about cpu and ram its getting killed before it can load all checkpoints

**Comment by KzZheng** [comment]
If you load the model on one GPU, it will take nearly 23 GB of RAM. We use AMD EPYC 7702P 64-Core Processor CPU.
