### ISSUE TITLE
How do model output interleaved text-image with multimodal input?

### ISSUE THREAD

**Issue by URRealHero** [eric-ai-lab/MiniGPT-5#52]
Does the model require further finetune? I'm wondering why the playground use a 'for' loop to generate a story

**Comment by URRealHero** [comment]
What I mean is how can it generate multi images with each image a caption. If I use a for loop, wouldn't the model repeatedly generate similar scene again and again? How did the `playground.py` ensure it can generate a sequence of story? How to make a coherent multi-images generation?

**Comment by KzZheng** [comment]
During the training, we take multiple images and text as context and let the model generate one text and one image each time. To generate a coherent multiple-turn output, you can take step 1's generation as context for step 2's generation.
